### ISSUE TITLE
Consider de-prioritizing search, particularly user serach

### ISSUE THREAD

**Issue by davidrunger** [msoanes/SilentIsland#1]
I don't think that searching through user bios will be too enjoyable of a feature for employers to play around with. Employers will have to guess at what keywords might be in the bios. You have a lot of great bonus features will probably deliver a bit more bang for your buck. I particularly like

Listenings history
Playlists and play queues
Pagination/infinite scroll
Recommendations based on past listens (item-based collaborative filtering) [TA: maybe you could base recommendations on "likes" and what other users have "liked", as well?]
Song and User comments [TA: especially for songs]
Song and User likes
User avatars [TA: this will add some]
Song cover images

**Comment by davidrunger** [comment]
If you plan for the users search to operate on bios, then it might not be very clear what is happening here:

![image](https://cloud.githubusercontent.com/assets/8197963/8069230/d403a01c-0ead-11e5-9342-77380bf6db40.png)

Since the relevant excerpts from the bios are not displayed, for example, it might not be very clear why any given user is showing up as one of the search results. It might even make your search appear to be random or broken.

**Comment by msoanes** [comment]
Thanks for the feedback, that's a very good point. I've adjusted my Phase 5 plan to be an implementation of play queues instead, and added a wireframe to show what it might look like.
