### ISSUE TITLE
Possibly consolidate users#search and songs#search into a single controller action, searches#search?

### ISSUE THREAD

**Issue by davidrunger** [msoanes/SilentIsland#7]
![image](https://cloud.githubusercontent.com/assets/8197963/8069056/ba340fce-0eac-11e5-94d0-492a62733ea5.png)

If the user results and the song results are fetched in separate AJAX requests, what happens if the songs results come back like 1.5 seconds before the users results come back? Then there might be an unpleasant and unexpected re-arranging of the page as the user search results are rendered onto the page.

There is also a small bit of overhead associated with any HTTP request, so, all things being equal, it's better if you can make a single HTTP request instead of one. And if there is no case where you will be specifically visiting either users#search or songs#search, and if instead the search actions are always hit at the same time, it might make sense to consolidate them.

**Comment by davidrunger** [comment]
I guess this is all moot, though, if you go with my other suggestion of maybe not even implementing users search.

**Comment by msoanes** [comment]
It is moot at this point, since I'm going with another feature for phase 5, and have search as a much lower priority. I think you're right, it's not as interesting for someone using the site as some of the others could be.
